version: '3.8'
services:
  mongo:
    image: mongo
    container_name: pcideal_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: pcideal
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  mongodb_data: